### PR TITLE
OCPBUGS-41961: Fix webhook manifest generation

### PR DESCRIPTION
**Pull request by tmshort**
Update the webhook's namespace and add openshift cert annotations
Update the generate script to properly use the TMP_ROOT directory
Consolidate the namespace to one variable

### CODE REVIEW

**Comment by kuiwang02** [comment]
pre-verify it with pass.

/label qe-approved

**Comment by tmshort** [comment]
`ci/prow/openshift-e2e-aws-techpreview` is expected to fail until https://github.com/openshift/release/pull/56998 is merged.

**Review by m1kola — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
