### PR TITLE
NO-ISSUE: Synchronize From Upstream Repositories

### PR DESCRIPTION
**Pull request by tmshort**
The downstream repository has been updated through the following upstream commit:

| Date | Commit | Author | Message |
| -    | -      | -      | -       |
|2024-07-10 08:07:15|[operator-framework/catalogd@13002de](https://github.com/operator-framework/catalogd/commit/13002de7588ee443234d394bb0cbcdf49c5814ba)|dependabot[bot]|:seedling: Bump google.golang.org/grpc from 1.64.0 to 1.64.1 (#303)|
||[upstream commit list](https://github.com/operator-framework/catalogd/commits/13002de7588ee443234d394bb0cbcdf49c5814ba)|||

The `vendor/` directory has been updated and the following commits were carried:

| Date | Commit | Author | Message |
| -    | -      | -      | -       |
|2024-07-08 09:53:23|[openshift/operator-framework-catalogd@71ec922](https://github.com/openshift/operator-framework-catalogd/commit/71ec922a44a1999fe2b166009129c3e841b53ddd)|dtfranz|UPSTREAM: <carry>: Add OpenShift specific files|
|2024-07-08 09:54:30|[openshift/operator-framework-catalogd@43cc752](https://github.com/openshift/operator-framework-catalogd/commit/43cc75217f50a40438b7ef6cda3730bd5b5e2ab5)|Todd Short|UPSTREAM: <carry>: Update generate-manifests.sh (squashed with above)|
|2024-07-08 09:53:24|[openshift/operator-framework-catalogd@f60e3bf](https://github.com/openshift/operator-framework-catalogd/commit/f60e3bf39c7800c5d1d42a0dd9c062ee45b4320c)|Alexander Greene|UPSTREAM: <carry>: Drop commitchecker|
|2024-07-08 09:53:24|[openshift/operator-framework-catalogd@2b54eac](https://github.com/openshift/operator-framework-catalogd/commit/2b54eac157f66ec4c13e8837c088d5d2e97c7037)|AOS Automation Release Team|UPSTREAM: <carry>: Updating ose-olm-catalogd-container image to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/e5df10e41b14c724468c8f78e2690f219279bfc4/images/ose-olm-catalogd.yml|
|2024-07-08 09:53:25|[openshift/operator-framework-catalogd@b624d77](https://github.com/openshift/operator-framework-catalogd/commit/b624d775fe8fc3e2dfb65bda8c60f12999b0c77e)|AOS Automation Release Team|UPSTREAM: <carry>: Updating ose-olm-catalogd-container image to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/4022cd290f00a44d667dda03f2d78d84a488c7ed/images/ose-olm-catalogd.yml|
|2024-07-08 09:53:25|[openshift/operator-framework-catalogd@002a40e](https://github.com/openshift/operator-framework-catalogd/commit/002a40e6089e31951d0cb0b921494f7ceddc6a48)|Andy Goldstein|UPSTREAM: <carry>: Remove ncdc from OWNERS|
|2024-07-08 09:53:25|[openshift/operator-framework-catalogd@cd9f9f1](https://github.com/openshift/operator-framework-catalogd/commit/cd9f9f1d3c6f0303746f75d86677fec5df68e835)|Mikalai Radchuk|UPSTREAM: <carry>: update owners|
|2024-07-08 09:54:04|[openshift/operator-framework-catalogd@b3b4935](https://github.com/openshift/operator-framework-catalogd/commit/b3b4935e1981d3ffe5c5bded2d557c21d1c19b39)|AOS Automation Release Team|UPSTREAM: <carry>: Updating ose-olm-catalogd-container image to be consistent with ART for 4.16 Reconciling with https://github.com/openshift/ocp-build-data/tree/cd35345d4d061d63bddd2911a9c77149106dee55/images/ose-olm-catalogd.yml|
|2024-07-08 09:54:29|[openshift/operator-framework-catalogd@2d4910d](https://github.com/openshift/operator-framework-catalogd/commit/2d4910df806584c666fdbbab5df57b23a71aad10)|Ilias Rinis|UPSTREAM: <carry>: manifests: set required-scc for openshift workloads|
|2024-07-08 09:55:32|[openshift/operator-framework-catalogd@791d978](https://github.com/openshift/operator-framework-catalogd/commit/791d9786c5b4d0e515087ef834527772ec143dc8)|Todd Short|UPSTREAM: <carry>: Update CI base to 1.22/4.17|
|2024-07-08 09:55:47|[openshift/operator-framework-catalogd@82089bb](https://github.com/openshift/operator-framework-catalogd/commit/82089bb3f5062924b46a1e12ad7c7c41f1db1b82)|Todd Short|UPSTREAM: <carry>: Update manifest generation for catalogd|
|2024-07-09 04:18:50|[openshift/operator-framework-catalogd@b4f5a62](https://github.com/openshift/operator-framework-catalogd/commit/b4f5a62a18768aa81498c8c9bf90b8b30f9b140e)|everettraven|UPSTREAM: <carry>: add everettraven to approvers+reviewers|
|2024-07-11 17:28:04|[openshift/operator-framework-catalogd@f6b28d0](https://github.com/openshift/operator-framework-catalogd/commit/f6b28d0f6e128f6dafceddb6a4b09a444bc6ef15)|Tayler Geiger|UPSTREAM: <carry>: add openshift kustomize overlay|

This pull request is expected to merge without any human intervention. If tests are failing here, changes must land upstream to fix any issues so that future downstreaming efforts succeed.

/cc @openshift/openshift-team-operator-runtime
/cc @openshift/openshift-team-operator-ecosystem

### CODE REVIEW

**Comment by joelanford** [comment]
Added `acknowledge-critical-fixes-only` because this unblocks our nightly downstream sync.

**Comment by kevinrizza** [comment]
/retitle OCPBUGS-29705: Synchronize From Upstream Repositories

**Pull request merged**
