### PR TITLE
NO-JIRA: add tmshort to approvers

### PR DESCRIPTION
**Pull request by grokspawn**

### CODE REVIEW

**Comment by tmshort** [comment]
LGTM, but should wait until after the #33 is merged. (so purposely not slashing)

**Comment by grokspawn** [comment]
@tmshort is it time?  #33 merged.

**Comment by grokspawn** [comment]
@tmshort  how about now? 😉

**Comment by tmshort** [comment]
Ooo... forgot about this. 
/lgtm

**Review by tmshort — APPROVED** [review]

**Pull request merged**
