### PR TITLE
OPRUN-3566: UPSTREAM: <carry>: Add global-pull-secret flag

### PR DESCRIPTION
**Pull request by m1kola**
Pass global-pull-secret to the manager container.

### CODE REVIEW

**Comment by m1kola** [comment]
At this point we have a flag and all the required RBAC, but I think both catalogd and operator-controller need to be built with `containers_image_openpgp` build tag.

**Comment by m1kola** [comment]
Ah, it looks like we do build with `containers_image_openpgp` already. Something else is off: unpack fails like so:

```yaml
    conditions:
    - lastTransitionTime: "2024-10-11T08:13:02Z"
      message: 'source catalog content: error copying image: copying system image
        from manifest list: Can not copy signatures to oci:/tmp/oci-layout-redhat-community-operators658406605:registry.redhat.io/redhat/community-operator-index@sha256:907fece168a3753e606a31c9c976ef49153487205e9bce8481ea5c1e0bf7f905:
        Pushing signatures for OCI images is not supported'
      observedGeneration: 1
      reason: Retrying
      status: "True"
      type: Progressing

```

**Comment by m1kola** [comment]
Ok, so it fails because on OCP we have this: `/etc/containers/registries.d/registry.redhat.io.yaml`:

```
docker:
     registry.redhat.io:
         sigstore: https://registry.redhat.io/containers/sigstore
```

With this config in place image copying fails. Now need to figure out how to make it work.

**Comment by m1kola** [comment]
With this patch to upstream it works, but not sure if this is a proper solution. Need to dig a bit more on implications of doing this.

```diff
diff --git a/internal/source/containers_image.go b/internal/source/containers_image.go
index cf40b62..44458de 100644
--- a/internal/source/containers_image.go
+++ b/internal/source/containers_image.go
@@ -130,7 +130,8 @@ func (i *ContainersImageRegistry) Unpack(ctx context.Context, catalog *catalogdv
        //
        //////////////////////////////////////////////////////
        if _, err := copy.Image(ctx, policyContext, layoutRef, dockerRef, &copy.Options{
-               SourceCtx: srcCtx,
+               RemoveSignatures: true,
+               SourceCtx:        srcCtx,
        }); err != nil {
                return nil, fmt.Errorf("error copying image: %w", err)
        }
```

**Comment by tmshort** [comment]
Where are we on this @m1kola?

**Comment by m1kola** [comment]
@tmshort the latest is in the comments above. Pull secret works, but catalogd (and operator-controller too, I suspect) will fail to unpack images due to this issue.

**Comment by m1kola** [comment]
https://github.com/operator-framework/catalogd/pull/431 and https://github.com/operator-framework/operator-controller/pull/1369 should resolve the blocker after syncing downstream.

**Comment by m1kola** [comment]
This now (temporary) includes #78. Once #78 merges we will need to rebase on top of `main`.

**Review by anik120 — APPROVED** [review]
/lgtm

**Pull request merged**
