### PR TITLE
[release-4.15] OCPBUGS-36885: Set required-scc for openshift workloads

### PR DESCRIPTION
**Pull request by ShazaAldawamneh**
[OCPBUGS-36885](https://issues.redhat.com/browse/OCPBUGS-36885#:~:text=OpenShift%20Bugs-,OCPBUGS%2D36885,-%5B4.15.z%5D%20SCC)

Manual cherry-pick of [#50](https://github.com/openshift/operator-framework-catalogd/pull/50)

### CODE REVIEW

**Comment by grokspawn** [comment]
Hi @ShazaAldawamneh!  Thanks for the backport.  It looks like the only issue with the PR is that the commit is not labeled in a way that lets our automated downstreamer know how to handle the commit.  You would need to re-label the commit to comply with [the instructions](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_operator-framework-catalogd/58/pull-ci-openshift-operator-framework-catalogd-release-4.15-verify-commits/1815730712574169088#1:build-log.txt%3A24)

**Comment by grokspawn** [comment]
@ShazaAldawamneh is this PR ready to merge?  The title still has '[WIP]' so the bot is holding it.

**Comment by ShazaAldawamneh** [comment]
@grokspawn I need the following labels, lgtm, backbort-risk-assessed and cherry-pick-approved please.

**Comment by jianzhangbjz** [comment]
Test pass, see: https://issues.redhat.com/browse/OCPBUGS-36885
/lgtm
/label qe-approved
/label cherry-pick-approved

**Pull request merged**
