### PR TITLE
OCPBUGS-29705:UPSTREAM: <carry>: lower the CPU requests

### PR DESCRIPTION
**Pull request by jianzhangbjz**
As title, address https://issues.redhat.com/browse/OCPBUGS-29705

### CODE REVIEW

**Comment by grokspawn** [comment]
/approve cancel
/lgtm cancel

The way we need to do this is to adjust config/manager/manager.yaml upstream, then downstream it.  This is likely not limited to just OCP, and this would follows the general approach of a downstream+drop instead of a carry commit.

**Comment by grokspawn** [comment]
https://github.com/operator-framework/catalogd/pull/298 should resolve this, and standard downstreaming sync for v1 should handle merging to this project.

**Comment by kevinrizza** [comment]
closing this as the upstream commit merged as part of https://github.com/openshift/operator-framework-catalogd/pull/57

**Comment by kevinrizza** [comment]
actually, looks like I don't have permission to close it. @jianzhangbjz can you close this pr so that the automation can move the bug to modified?

https://github.com/openshift/operator-framework-catalogd/pull/57#issuecomment-2229000216

**Comment by jianzhangbjz** [comment]
Sure, closed it.

**Pull request closed without merging**
